### ISSUE TITLE
Choosing background image or folder from local path results in `Error: [UriError]`

### ISSUE THREAD

**Issue by flatypus** [KatsuteDev/Background#100]
### Operating System

Arch Linux

### VSCode Version

1.75.1

### Extension Version

v2.4.1

### Issue

Picking a background from a folder, such as /home/[user]/wallpapers/**, or a specific file /home/[user]/wallpapers/background.jpg, throws 
```
[error] Error: [UriError]: If a URI does not contain an authority component, then the path cannot begin with two slash characters ("//")
    at P (/opt/visual-studio-code/resources/app/out/vs/code/electron-main/main.js:20:68898)
    at new f (/opt/visual-studio-code/resources/app/out/vs/code/electron-main/main.js:20:69806)
    at new w (/opt/visual-studio-code/resources/app/out/vs/code/electron-main/main.js:20:71187)
    at w.with (/opt/visual-studio-code/resources/app/out/vs/code/electron-main/main.js:20:70233)
    at P.uriToFileUri (/opt/visual-studio-code/resources/app/out/vs/code/electron-main/main.js:21:4231)
    at p.j (/opt/visual-studio-code/resources/app/out/vs/code/electron-main/main.js:81:95062)
    at p.i (/opt/visual-studio-code/resources/app/out/vs/code/electron-main/main.js:81:94568)
    at Function.<anonymous> (/opt/visual-studio-code/resources/app/out/vs/code/electron-main/main.js:81:94019)
```
VSCode was installed from the arch user repository, since installing from tar or from snap didn't seem to work (permissions error).

The extension works fine with urls, however.

### How to replicate

background => configure, and select folder or file. 
background => install, checking the main output tab shows this error, and no background is updated.

**Comment by Katsute** [comment]
Caused by this line:

https://github.com/KatsuteDev/Background/blob/d5eb6c82ffe44e6d781745f90de817623b3da6bc/src/lib/glob.ts#L54

Windows: `C://Users/*/Pictures/**` → `vscode-file://vscode-app/C://Users/*/Pictures/**`

Linux: `/home/*/pictures/**` → `vscode-file://vscode-app//home/*/pictures/**`

Linux has no concept of drive letters causing an erroneous double slash.

A new PR will be opened for this fix.
