### ISSUE TITLE
Fails on Linux with EACCES: permission denied, copyfile

### ISSUE THREAD

**Issue by robinfriedli** [KatsuteDev/Background#118]
### Operating System

Pop!_OS 22.04 LTS

### VSCode Version

1.76.1 (Sandboxed: No)

### Extension Version

v2.5.1

### Issue

My configuration works on Mac but fails on PopOS with the following error

```
2023-03-10 23:54:50.487 [error] Activating extension Katsute.code-background failed due to an error:
2023-03-10 23:54:50.487 [error] Error: EACCES: permission denied, copyfile '/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js' -> '/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main-backup.js'
	at Object.copyFileSync (node:fs:2804:3)
	at Object.func (node:electron/js2c/asar_bundle:5:1812)
	at activate (/home/robinfriedli/.vscode/extensions/katsute.code-background-2.5.1/dist/extension.js:53:24)
	at Ui.db (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:108:14833)
	at Ui.cb (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:108:14532)
	at /usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:108:12550
	at async f.n (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:94:6818)
	at async f.m (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:94:6781)
	at async f.l (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:94:6238)
```

Not sure if this is related to #92

### How to replicate

Try to activate extension on PopOS or quite probably other distros

**Comment by Katsute** [comment]
Related: #97 #104

Sudo write is not being promoted for backup writes.

https://github.com/KatsuteDev/Background/blob/main/src/extension.ts#L51-L79
